// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncer) DeepCopyInto(out *VaultSyncer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncer.
func (in *VaultSyncer) DeepCopy() *VaultSyncer {
	if in == nil {
		return nil
	}
	out := new(VaultSyncer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultSyncer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncerList) DeepCopyInto(out *VaultSyncerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultSyncer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncerList.
func (in *VaultSyncerList) DeepCopy() *VaultSyncerList {
	if in == nil {
		return nil
	}
	out := new(VaultSyncerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultSyncerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncerSpec) DeepCopyInto(out *VaultSyncerSpec) {
	*out = *in
	if in.DeploymentList != nil {
		in, out := &in.DeploymentList, &out.DeploymentList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StatefulsetList != nil {
		in, out := &in.StatefulsetList, &out.StatefulsetList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncerSpec.
func (in *VaultSyncerSpec) DeepCopy() *VaultSyncerSpec {
	if in == nil {
		return nil
	}
	out := new(VaultSyncerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncerStatus) DeepCopyInto(out *VaultSyncerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncerStatus.
func (in *VaultSyncerStatus) DeepCopy() *VaultSyncerStatus {
	if in == nil {
		return nil
	}
	out := new(VaultSyncerStatus)
	in.DeepCopyInto(out)
	return out
}
